### ISSUE TITLE
Support for mongo 4

### ISSUE THREAD

**Issue by emmansun** [microsoft/node-diagnostic-channel#59]
When will it support mongodb version >= 4?

**Comment by markwolff** [comment]
It should already support mongodb 4+. The things this library monitors is not your actual mongodb server, but the node.js driver (https://www.npmjs.com/package/mongodb?activeTab=versions). The latest version is 3.2.7 (beta is 3.3.0), which should work with mongo 4.

If you see an issue with monitoring your mongo 4 server (with the latest mongodb node.js driver), then you can open an issue about that, since it is probably a bug.
